### ISSUE TITLE
Steam keeps crashing when fossilize process "Deus Ex: Human Revolution - Director'cut" shaders

### ISSUE THREAD

**Issue by Saroumane** [ValveSoftware/Fossilize#107]
**What I see :**
Ubuntu 20.04 / Radeon RX 5700 XT / Mesa 20.2.1
Launch Steam in a terminal (I have no other programs running except Gnome System Monitor)
Go to "Shader Pre-Caching" Tab (I have already around 30 GB of shaders already cached)
I can see shader compilation for "Deus Ex: Human Revolution - Director'cut" : it goes steadily from 0% to 99% 
then Steam client crash with theses messages (which are fully reproduced each time) :

in the terminal : 
`OUT OF MEMORY! attempted allocation size: 1681471294 ****`

in .steam/error.log :
```
/data/src/tier0/memstd.cpp (2448) : Fatal Assertion Failed: OUT OF MEMORY
/data/src/tier0/memstd.cpp (2448) : Fatal assert failed: /data/src/tier0/memstd.cpp, line 2448.  Application exiting.

```

**During the shader processing :**
3 fossilize-replay are spawned
RAM Usage peaks at 4 GB (+ in Cache 7,5 GB) (Total RAM on this PC : 15,6 GB)
SWAP : not used (8 GB available)
CPU : 3 cores are used at 100% (Total number of cores on this PC : 12 cores)
Free space available for the Steam Library : 74 GB

![Screenshot from 2020-11-03 15-01-24](https://user-images.githubusercontent.com/22261137/97995149-6fc81800-1de6-11eb-9e99-211f4da6cab9.png)

![Screenshot from 2020-11-03 15-12-19](https://user-images.githubusercontent.com/22261137/97996076-a3577200-1de7-11eb-8b01-a4dc702cc98d.png)

The problem is worse than expected : If I try to uncheck ""Allow background processing of Vulkan shaders", then Steam instant crashes with same error messages than above. And when I relaunch Steam ""Allow background processing of Vulkan shaders" is still checked.

**Workaround :**
I guess the only way to make Steam usable again is to (try to) completely disable Shader Pre-caching or uninstall this game.
I uninstalled "Deus Ex: Human Revolution - Director'cut" and now Steam is processing shaders for others games.

**Comment by kakra** [comment]
You should at least run with a small swap file, not without any swap at all. Otherwise you'll give the kernel a hard time to find memory under allocation pressure. Also, please check if your system enabled zswap, and disable that.

**Comment by Saroumane** [comment]
Sorry If I was not clear, I edit : no swap was used (but I have 8 GB of swap available)

**Comment by kakra** [comment]
Could you check if zswap is enabled and its pool size:
```bash
# grep '^' /sys/module/zswap/parameters/*
```

**Comment by Saroumane** [comment]
I have never heard about it before :

```
grep '^' /sys/module/zswap/parameters/*
/sys/module/zswap/parameters/accept_threshold_percent:90
/sys/module/zswap/parameters/compressor:lzo
/sys/module/zswap/parameters/enabled:N
/sys/module/zswap/parameters/max_pool_percent:20
/sys/module/zswap/parameters/same_filled_pages_enabled:Y
/sys/module/zswap/parameters/zpool:zbud

```
What do you think ?

**Comment by kakra** [comment]
@Saroumane Well, that's actually memory compression. Instead of sending pages directly to swap, "zbud" will compress two separate pages down into one page, achieving a compression of exactly 2:1 for compressible pages (many are). These "buddy pages" are then stored in the swap cache pool. No disk IO was caused until now. It will keep a dynamic pool of up to 20% of RAM by default, after which compressed pages may be swapped to disk. While the transparent handling of swap pages is a stable kernel feature (i.e. data centers can use remote swap that way), the zbud compression feature isn't. As such, there are a lot of side effects that may not play well under memory exhaustion, leading to situations that you found: high cache usage but memory allocation fails. This is mainly a feature to reduce write wear with swap on SSD. Some distributions enable it by default (or make it very easy to enable). IMO, the default pool size is too high for a desktop system (I'm using 5% in a 32 GB system), or at least it's very hard to find a good default value because this totally depends on what workload you're going to apply to the system.

But zswap is turned off for you. So you should be fine.

**Additional note:** Above description is very simplified, zbud is actually the pool allocator (not the compressor) which is a buddy allocator that holds space for two compressed pages to fit within one page and put it in transient memory (memory which is there but not directly accessible by the CPU), that transient part is a stable kernel feature and can also be used to migrate RAM of running VMs from one host to another (live migration), or to borrow swap from another machine in a server farm over high-throughput network. There's also zbud3 putting exactly three pages into one, achieving compression of 3:1 that way. Getting a page back from transient memory means it will need to get two (or three for zbud3) free pages from RAM and uncompress the buddy page again. This introduces some fragile implications under high memory contention.

Another problem you may be facing is memory fragmentation with transparent huge pages enabled. Please look at:
```bash
# grep '^' /sys/kernel/mm/transparent_hugepage/**
```

**Comment by Saroumane** [comment]
Thanks for explanation. I guess it's not a feature for desktop end-user like me, or maybe as a desperate action if I lack physical RAM (but with big shortcomings)

Anyway :
```
$ grep '^' /sys/kernel/mm/transparent_hugepage/**
/sys/kernel/mm/transparent_hugepage/defrag:always defer defer+madvise [madvise] never
/sys/kernel/mm/transparent_hugepage/enabled:always [madvise] never
/sys/kernel/mm/transparent_hugepage/hpage_pmd_size:2097152
grep: /sys/kernel/mm/transparent_hugepage/khugepaged: Is a directory
/sys/kernel/mm/transparent_hugepage/shmem_enabled:always within_size advise [never] deny force
/sys/kernel/mm/transparent_hugepage/use_zero_page:1

```

**Comment by kakra** [comment]
`enabled` = madvise looks fine, there should be no problem with memory fragmentation.

Did you use any "tuning" tricks like changing the swappiness parameter? Which kernel version are you using?

**Comment by Saroumane** [comment]
After I uninstalled the game and reboot, I have no more any crash problems... And the game plays normally.
But I don't know if Steam has already tried to compile shaders for this game.
Can I force shader compilation for a game ?
By the way, do you know where the shader cache is located ? I used to think it's in "~/.steam/steamapps/shadercache" but it's not. (This folder is only 3.6 GB for me, whereas I have 30GB shaders cache according to Steam UI)

I don't think I have tuning tricks for RAM or CPU
for the Ryzen CPU, my governors are on "ondemand"
for the swappiness (default value) :
```
$ cat /proc/sys/vm/swappiness
60
```
My kernel : 5.8.16-050816-generic

**Comment by kakra** [comment]
I wonder if there was something broken in the shader db files that made fossilize crash. Uninstalling the game probably removed the shader db, too. And so it started back from a clean state. May have been enough to just clear the shader cache directory instead. I've seen similar problems before when games still used one shared cache, I needed to clear `~/.nv` to prevent DXVK from crashing with an out of memory error. This was before fossilize was introduced.
