### ISSUE TITLE
Feature Request: Save processed shaders to disk, prevent re-processing on each run

### ISSUE THREAD

**Issue by ctjlewis** [ValveSoftware/Fossilize#109]
Please let me know if this is not the correct repo - I had no idea where to make a note of this.

It takes about 10-20 minutes for fossilize to process GTA V shaders on my machine, and this happens each time I start the game. It seems redundant to do this process more than once, and it seems to me that naively, a user option could be added to save the processed shaders on-disk so that you are not running the same computations each time a game is started.

![image](https://user-images.githubusercontent.com/1657236/98620245-88df3600-22ca-11eb-85ef-6e5eba1ab16a.png)

This is a fantastic piece of technology however, and thank you to everyone at Valve for maintaining it.

**Comment by kisak-valve** [comment]
Hello @ctjlewis, this isn't a valid feature request because fundamentally this is what Steam's shader pre-caching does in the first place. It replays collected shaders on your system so that the video driver caches them with the video driver's on-disk cache feature. Some games have a massive amount of shaders, and it's easier for more shaders to be discovered causing a small change in a large set of shaders shared by Steam's shader pre-caching system, but if the shaders are already stored in the video driver's on-disk cache, then it should be fairly quick to re-process them.

It sounds like you've encountered the issue being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/7306. Closing as a duplicate.
