### ISSUE TITLE
Dota 2 Vulkan shader cache duration?

### ISSUE THREAD

**Issue by Tacklebox** [ValveSoftware/Fossilize#113]
Shaders seem to be recompiled almost every time I launch the game. It used to be once per update more or less but now if the game is closed for more than an hour or so I have to wait for "Processing Vulkan Shaders"

I had temporarily set the launch flag to not cache while debugging another issue (turned out to be an issue with gamemoderun) but have since removed it. Caching has not worked since.

**Comment by Saroumane** [comment]
For what it's worth : I tried to redownload, then compile all my games from an clean state : empty `shadercache`. (And I opened a bug about  the size reported by Steam client https://github.com/ValveSoftware/steam-for-linux/issues/7533 ). The compiling part took about 20 hours. A few hours after that, I restarted Steam client and it decided to start to recompile every game...

**Comment by jatin-cbs** [comment]
@Tacklebox  In my case -vulkan_disable_steam_shader_cache   This launch option did nothing it still processes it on every launch so i have to wait a long time, and also if I have to restart my game for any reason (dota update) It doesn't even let me skip.. So i have to restart steam in order to do that. And this is not nvidia specific as I am on AMD with latest mesa-git.

**Comment by le5h** [comment]
problem still exists
20 minutes on ryzen 5700
1 hour on intel 6300
