### ISSUE TITLE
fossilized_repla freq prevents clean system shutdown/restart

### ISSUE THREAD

**Issue by jarrard** [ValveSoftware/Fossilize#140]
#### Your system information

* Steam client version (build number or date):  Aug 20 2021, at 20:39:31
* Distribution (e.g. Ubuntu): Arch (via EndeavourOS)
* Opted into Steam client beta?: YES
* Have you checked for system updates?: YES

#### Please describe your issue in as much detail as possible:
Noticing lately that my system will take a long time to restart or shutdown sometimes because steams fossilized_repla process refuses to terminate or be killed. System just forced to wait until its finished. 

https://gist.github.com/jarrard/83901432e10599bab09c96d6ba471f0d

#### Steps for reproducing this issue:

1. Restart or Shutdown

**Comment by 0x0015** [comment]
Hello,  I am have recently (within the last year) started having this issue on both of my computers (one nvidia graphics, the other amd; both running up to date arch).


![20241204_002016](https://github.com/user-attachments/assets/e8e86935-24c5-4e6b-9fab-a358214b5a33)

The only other weird symptom I'm getting is that while fossilize is running (I can only presume it's running because I can't check, but my natural response upon seeing this is to reboot, and I get hung up there) certain commands (pidof, killall, htop) hang (not sure if there's any relation or if this should be it's own issue).
